# Generated by Django 6.0.6 on 2026-06-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_certificate_qr_code_alter_certificate_certificate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
